name: Build-Lean-lede
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Build-Lean-lede.yml'
#      -  'lean-lede/x86_64/.config'
 #     -  'lean-lede/rpi4/.config'
  #    -  'lean-lede/rpi/.config'
   #   -  'lean-lede/rpi32/.config'
      -  'lean-lede/mt7621/.config'
  schedule:
        - cron: 0 */4 * * *

jobs:
  MT7621:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/gaoadmin/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone source and install
      run: |
        git clone https://github.com/gaoadmin/lede
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Download and Load custom configuration
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/gaoadmin/My-action/master/lean-lede/mt7621/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/gaoadmin/My-action/master/lean-lede/diy.sh)
        ./scripts/feeds install -a
        make defconfig
        
    - name: Download package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-core or Single core compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j1 V=s
        sudo df -h
        
    - name: Setup Upload dictionary
      if: always()
      run: |
        cd lede/bin/
        rm -rf packages
        rm -rf targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-initramfs-kernel.bin
        rm -rf targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-initramfs-kernel.bin
        rm -rf targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-factory.bin
        rm -rf targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-kernel1.bin
        rm -rf targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-rootfs0.bin
        pwd
        ls -l
        echo "::set-env name=FIRMWARE::$(pwd)"
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: ac2100
        path: ${{ env.FIRMWARE }}
        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install coscmd
      run: |
        pip install coscmd

    - name: Upload to COS
      env:
        COS_BUCKET_NAME: openwrt-1251594457
        COS_BUCKET_LOCATION: na-toronto
      run: |
        cd lede/bin/
        coscmd config -a ${{secrets.COS_SECRET_ID}} -s ${{secrets.COS_SECRET_KEY}} -b ${COS_BUCKET_NAME} -r ${COS_BUCKET_LOCATION} -m 10
        coscmd upload -r -s lede/bin/ /
