name: Build-Lean-lede
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Build.yml'
#      -  'lean-lede/x86_64/.config'
 #     -  'lean-lede/rpi4/.config'
  #    -  'lean-lede/rpi/.config'
   #   -  'lean-lede/rpi32/.config'
      -  'lean-lede/mt7621/.config'
  schedule:
        - cron: 0 3 * * *
jobs:
  MT7621:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/gaoadmin/My-action/master/lean-lede/prenv.sh)
        
    - name: Clone source and install
      run: |
        git clone https://github.com/gaoadmin/lede
        cd lede
        rm -rf .conf
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Download and Load custom configuration
      run: |
        cd lede
        curl -fsSL https://raw.githubusercontent.com/gaoadmin/My-action/master/lean-lede/mt7621/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/gaoadmin/My-action/master/lean-lede/diy.sh)
        ./scripts/feeds install -a
        make defconfig

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install coscmd
      run: |
        pip install coscmd
        
    - name: Download package
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-core or Single core compile
      run: |
        cd lede
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(($(nproc) + 1)) V=s || make -j1 V=s
        sudo df -h
        
    - name: Setup Upload dictionary
      if: always()
      run: |
        cd lede/bin/packages
        zip -r -o -q MT7621-Package.zip . -i *.ipk
        cp MT7621-Package.zip ../targets/ramips/mt7621/
        cd ../
        rm -rf packages
        rm -rf targets/ramips/mt7621/packages
        rm -rf "targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-factory.bin"
        rm -rf "targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-rootfs0.bin"
        rm -rf "targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-kernel.bin"
        rm -rf "targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-squashfs-kernel1.bin"
        rm -rf "targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-ac2100-initramfs-kernel.bin"
        sleep 5s
        echo "::set-env name=FIRMWARE::$(pwd)" 
        
    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: mt7621
        path: ${{ env.FIRMWARE }}
        
    - name: Upload firmware to Download Station (Without packages)
      env:
        COS_BUCKET_NAME: openwrt-1251594457
        COS_BUCKET_LOCATION: na-toronto
      if: success()
      run: |
        coscmd config -a ${{secrets.COS_SECRET_ID}} -s ${{secrets.COS_SECRET_KEY}} -b ${COS_BUCKET_NAME} -r ${COS_BUCKET_LOCATION} -m 10
        cd lede/bin/targets/ramips/mt7621/
        ls -l
        zip -r -o -q mt7621.zip . -x MT7621-Package.zip
        coscmd upload -r -s mt7621.zip /
        coscmd upload -r -s MT7621-Package.zip /
