name: Deloy to COS
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: print pwd testing
      run: |
        pwd
        mkdir -p xxx/xxx
        cd xxx
        echo xxxxxssx>xxx/aa.txt
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install coscmd
      run: |
        pip install coscmd
    - name: deploy
      env:
        COS_BUCKET_NAME: openwrt-1251594457
        COS_BUCKET_LOCATION: na-toronto
      run: |
        coscmd config -a ${{secrets.COS_SECRET_ID}} -s ${{secrets.COS_SECRET_KEY}} -b ${COS_BUCKET_NAME} -r ${COS_BUCKET_LOCATION} -m 10
        coscmd upload -r -s xxx/ /
